[package]
name = "rustymines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
factory = "*"
grid = { git = "https://github.com/conqp/grid.git", branch = "main" }
