[package]
name = "rustymines"
version = "1.1.3"
edition = "2021"
authors = ["Richard Neumann <mail@richard-neumann.de>"]
description = "A mine sweeping game with optional duds."
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/conqp/rustymines/"
repository = "https://github.com/conqp/rustymines/"
documentation = "https://docs.rs/rustymines"
keywords = [ "mine", "mines", "sweeper", "game", "console"]
categories = ["games"]

[dependencies]
clap = { version = "*", features = ["derive"] }
grid2d = "0.2.1"
itertools = "0.10.5"
rand = "0.8.5"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
