[package]
name = "rustymines"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
rand = "*"
grid = { git = "https://github.com/conqp/grid.git", branch = "main" }
clap = { version = "*", features = ["derive"] }

[profile.release]
strip = true
#opt-level = "s"
lto = true
codegen-units = 1