[package]
name = "rustymines"
version = "1.1.3"
edition = "2021"
authors = ["Richard Neumann"]
description = "A mine sweeping game written in Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
rand = "*"
grid2d = "*"
clap = { version = "*", features = ["derive"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
